import type { JobPosition } from '../types';

export const mockJobs: JobPosition[] = [
    {
        id: "68ef68d6065ad9d4ee0dd3f4",
        position_name: "Bancassurance Officer (BO)",
        description: `<p>Guardian Life is looking for a <strong>Bancassurance Officer (BO)</strong>.</p>
<p>This role will independently acquire and grow new business under the guidance and leadership of the Area Manager or Head of Business. The BO shall engage with the appointed bank branch officials to achieve the assigned branch's overall business goals and targets.</p>
<p><br> ◉ Close the leads generated by the bank's officials into the Life Insurance Business.<br> ◉ Achieve monthly/annual sales target i.e. First Year Premium [FYP].<br> ◉ Ensure collection of renewal premiums from assigned banks/NBFI.<br> ◉ Maintain a healthy and working relationship with the bank officials and customers.<br> ◉ Provide timely support and service to the bank officials and customers.</p>
<p><br> 𝐄𝐱𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞<br> ◉ At most 1 year<br> ◉&nbsp;The applicants should have experience in the following business area(s): Banks<br> ◉&nbsp;Freshers are also encouraged to apply.</p><p><br></p>
<p>𝐀𝐝𝐝𝐢𝐭𝐢𝐨𝐧𝐚𝐥 𝐑𝐞𝐪𝐮𝐢𝐫𝐞𝐦𝐞𝐧𝐭𝐬<br> ◉ Age 26 to 30 years<br> ◉ Experience in sales of financial products and services will be given preference.<br> ◉ Candidates from the financial industry's direct sales team shall get priority.<br> ◉ Must be honest, accountable, and a team player with excellent work ethics and moral values.<br> ◉ Knowledge of Microsoft Office and Outlook.<br> ◉ Require Business communication skills.<br> ◉ Should have relationship management skills.<br> ◉ Willing to travel for work.</p><p><br></p><p><strong>Compensation &amp; Other Benefits</strong><br>◉ Weekly 2 holidays<br>◉ Festival Bonus: 2<br>◉ Incentives for achieving the target, Career Progression<br></p>


<p><br></p><p>𝐖𝐨𝐫𝐤𝐩𝐥𝐚𝐜𝐞<br> Work at the office</p>
<p><strong>&nbsp;</strong><br></p>
<p><strong>Employment Status</strong></p>
<p>Contractual</p>
<p>&nbsp;<br></p>
<p><strong>Job Location</strong></p>
<p>Anywhere in Bangladesh<br> </p>
<p>If you believe you have the potential to excel in this role, please send your CV to: <a href="mailto:career@guardianlife.com.bd">career@guardianlife.com.bd</a></p>`,
        address: "Dhaka",
        job_type: "Contractual",
        job_status: true,
        department_id: "68ef679948dcb5c4be6fb509",
        created_at: "2025-10-15T09:26:46.897Z",
        updated_at: "2026-01-07T04:22:52.787Z"
    }
];
