
import type { ChairmanMessageData } from "../types";



export const MOCK_CHAIRMAN_MESSAGE_DATA: ChairmanMessageData = {
    title: "CHAIRMAN'S MESSAGE",
    paragraphs: [
        "GUARDIAN LIFE INSURANCE LIMITED IS HERE TO RADICALLY CHANGE THE TRADITIONAL APPROACH TO LIFE INSURANCE, INJECTING NEW ENERGY, VITALITY, AND PROFESSIONALISM INTO OUR RELATIONSHIP WITH OUR POTENTIAL CUSTOMERS. WE WISH TO ESTABLISH A NEW PARADIGM OF COMMITMENT, PROFESSIONALISM, INTEGRITY, AND DIGNITY IN THE PROVISION OF SECURITY FOR THE FUTURE OF OUR CLIENTS AND THEIR LOVED ONES. THIS IS OUR FIRM COMMITMENT. THE CUSTOMERS WILL BE THE PRINCIPAL STAKEHOLDERS OF GUARDIAN, MEMBERS OF GUARDIAN LIFE INSURANCE LIMITED. AS YOU KNOW, THE CHIEF SPONSORS OF THIS COMPANY, NAMELY BRAC, SQUARE, AND APEX ARE MARKET LEADERS IN THEIR FIELDS. THESE GIANTS OF THE INDUSTRY HAVE LONG GROWN UNDENIABLE BRAND HERITAGE. BESIDES, THE COMPANY HAS 3 (THREE) FOREIGN AND 2 (TWO) LOCAL PRIVATE ACUTE INVESTORS.",
        "ALL OF THESE COMPANIES ARE RENOWNED FOR THEIR GOOD GOVERNANCE AND IT IS ONLY FITTING THAT A LIFE INSURANCE COMPANY BEING SPONSORED BY THEM WILL WALK IN THE SAME DIRECTION. GUARDIAN LIFE ALSO HAS THE UNIQUE VISION OF SPREADING THE BENEFITS OF INSURANCE TO ALL SECTORS OF SOCIETY, AND THAT IS WHY THE COMPANY IS INTRODUCING THREE DIFFERENT CATEGORY PRODUCTS FOR THREE DIFFERENT TARGET MARKETS. THE COMPANY RECOGNIZES SOCIAL DEVELOPMENT AS A CORE BOTTOM-LINE TARGET AND IS STRIVING TO ACHIEVE THE TAG OF A CORPORATE SOCIAL CITIZEN, A MOVEMENT THAT WILL IMPROVE THE INDUSTRY FOR THE BETTER.",
        "THE LITTLE SAPLING WE PLANTED TODAY WITH ALL OF YOUR BLESSINGS WILL BECOME THE GIANT TREE UNDER WHOSE SHADE THE GUARDIAN FAMILY WILL FIND THE STRENGTH AND COURAGE TO MEET EVERY ADVERSITY WITH THE INSURANCE OF OUR CONSTANT SUPPORT."
    ],
    chairman: {
        name: "MR. SAMUEL S CHOWDHURY",
        designation: "CHAIRMAN",
        phone: "+8809612016622",
        email: "SAMUEL@GUARDIANLIFE.COM.BD",
        image_url: "/src/assets/images/chairman/chairman.png"
    }
};
