import type { HospitalApiSuccessResponse, HospitalType } from '../types';

export const mock_hospital_data: Record<HospitalType, HospitalApiSuccessResponse> = {
    national_hospital: {
        success: true,
        transaction_id: "GLIL-TXN-ID",
        data: [
            {
                country_name: null,
                hospital_name: "Apollo Hospital Dhaka",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Dhanmondi",
                address: "Plot 123, Road 8, Dhanmondi, Dhaka-1209",
                facilities: "Emergency care, ICU, Cardiology, Neurology, Orthopedics, Pediatrics, Maternity care, Laboratory services, Pharmacy, Blood bank",
                contact_person_phone_number: ["+880-2-12345678", "+880-2-87654321"],
                contact_person_email: ["info@apollohospital.com"],
                remarks: "24/7 emergency services available",
            },
            {
                country_name: null,
                hospital_name: "Bangladesh Medical College Hospital",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Dhanmondi",
                address: "House 23, Road 14/A, Dhanmondi, Dhaka-1209",
                facilities: "General medicine, Surgery, Gynecology, Pediatrics, ENT, Ophthalmology, Dental",
                contact_person_phone_number: ["+880-2-9124400"],
                contact_person_email: ["bmch@bmch.org"],
                remarks: null,
            },
            {
                country_name: null,
                hospital_name: "Square Hospital Ltd.",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Panthapath",
                address: "18/F, Bir Uttam Qazi Nuruzzaman Sarak, Dhaka-1205",
                facilities: "Cardiac surgery, Organ transplant, Cancer care, Dialysis, ICU, NICU, Laboratory, Pharmacy",
                contact_person_phone_number: ["+880-2-8159457", "+880-2-8144400"],
                contact_person_email: ["info@squarehospital.com"],
                remarks: "JCI Accredited Hospital",
            },
            {
                country_name: null,
                hospital_name: "United Hospital Ltd.",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Gulshan",
                address: "Plot 15, Road 71, Gulshan, Dhaka-1212",
                facilities: "Cardiology, Oncology, Neurosurgery, Orthopedics, Transplant, ICU, Emergency, Pharmacy",
                contact_person_phone_number: ["+880-2-8836000"],
                contact_person_email: ["info@uhlbd.com"],
                remarks: "24/7 emergency and trauma services",
            },
            {
                country_name: null,
                hospital_name: "Evercare Hospital Dhaka",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Bashundhara",
                address: "Plot 81, Block E, Bashundhara R/A, Dhaka-1229",
                facilities: "Multi-specialty, Cardiac, Oncology, Neurology, Bariatric surgery, Robotic surgery, NICU",
                contact_person_phone_number: ["+880-2-9821400"],
                contact_person_email: ["info@evercarebd.com"],
                remarks: "JCI Accredited – International standard care",
            },
            {
                country_name: null,
                hospital_name: "Chittagong Medical College Hospital",
                division_name: "Chittagong",
                district_name: "Chittagong",
                area_name: "Panchaish",
                address: "Medical College Road, Panchaish, Chittagong-4203",
                facilities: "Emergency, Surgery, Medicine, Gynecology, Pediatrics, Burn unit, Blood bank",
                contact_person_phone_number: ["+880-31-615701"],
                contact_person_email: ["cmch@cmch.gov.bd"],
                remarks: "Government teaching hospital",
            },
            {
                country_name: null,
                hospital_name: "Sylhet MAG Osmani Medical College Hospital",
                division_name: "Sylhet",
                district_name: "Sylhet",
                area_name: "Mirabazar",
                address: "Shahi Eidgah, Sylhet-3100",
                facilities: "Emergency, Surgery, Medicine, ENT, Ophthalmology, Dermatology, ICU",
                contact_person_phone_number: ["+880-821-713045"],
                contact_person_email: [],
                remarks: "Government hospital serving Sylhet division",
            },
            {
                country_name: null,
                hospital_name: "Rajshahi Medical College Hospital",
                division_name: "Rajshahi",
                district_name: "Rajshahi",
                area_name: "Laxmipur",
                address: "Laxmipur, Rajshahi-6000",
                facilities: "General medicine, Surgery, Pediatrics, Gynecology, Cardiology, Neurology",
                contact_person_phone_number: ["+880-721-775100"],
                contact_person_email: [],
                remarks: "Major referral hospital for Rajshahi division",
            },
        ],
    },

    national_diagnostic: {
        success: true,
        transaction_id: "GLIL-TXN-ID",
        data: [
            {
                country_name: null,
                hospital_name: "Popular Diagnostic Centre",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Dhanmondi",
                address: "House 16, Road 2, Dhanmondi, Dhaka-1205",
                facilities: "MRI, CT Scan, X-Ray, ECG, Echocardiography, Pathology, Endoscopy, Ultrasound",
                contact_person_phone_number: ["+880-2-9671011", "+880-1711-987654"],
                contact_person_email: ["info@populardiagnostic.com"],
                remarks: "ISO certified diagnostic centre",
            },
            {
                country_name: null,
                hospital_name: "Lab Aid Diagnostic",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Panthapath",
                address: "House 1, Road 4, Dhanmondi, Dhaka-1205",
                facilities: "Pathology, Biochemistry, Microbiology, Radiology, ECG, Stress Test, Spirometry",
                contact_person_phone_number: ["+880-2-8610793"],
                contact_person_email: ["labaid@labaidgroup.com"],
                remarks: "Branches available across Dhaka",
            },
            {
                country_name: null,
                hospital_name: "Impulse Diagnostic Centre",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Eskaton",
                address: "House 2, Eskaton Garden Road, Dhaka-1000",
                facilities: "MRI, CT, PET-CT, X-Ray, Mammography, Bone Densitometry, Pathology",
                contact_person_phone_number: ["+880-2-8315936"],
                contact_person_email: ["info@impulsebd.com"],
                remarks: null,
            },
            {
                country_name: null,
                hospital_name: "Medinova Medical Services",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Malibagh",
                address: "House 79/A, Road 7/A, Dhanmondi, Dhaka-1209",
                facilities: "Ultrasound, X-Ray, ECG, Pathology, Endoscopy, Colonoscopy, Bronchoscopy",
                contact_person_phone_number: ["+880-2-9352914"],
                contact_person_email: ["info@medinovabd.com"],
                remarks: "Multiple branches in Dhaka city",
            },
            {
                country_name: null,
                hospital_name: "Chittagong Diagnostic Centre",
                division_name: "Chittagong",
                district_name: "Chittagong",
                area_name: "GEC Circle",
                address: "GEC Circle, Nasirabad, Chittagong-4000",
                facilities: "MRI, CT Scan, X-Ray, Pathology, ECG, Ultrasound",
                contact_person_phone_number: ["+880-31-654321"],
                contact_person_email: [],
                remarks: null,
            },
            {
                country_name: null,
                hospital_name: "Sylhet Diagnostic Centre",
                division_name: "Sylhet",
                district_name: "Sylhet",
                area_name: "Amberkhana",
                address: "Amberkhana, Sylhet-3100",
                facilities: "CT Scan, X-Ray, Pathology, ECG, Ultrasound, Endoscopy",
                contact_person_phone_number: ["+880-821-718800"],
                contact_person_email: [],
                remarks: "Serving Sylhet and surrounding areas",
            },
        ],
    },

    international_hospital: {
        success: true,
        transaction_id: "GLIL-TXN-ID",
        data: [
            {
                country_name: "Singapore",
                hospital_name: "Singapore General Hospital",
                division_name: null,
                district_name: null,
                area_name: null,
                address: "Outram Road, Singapore 169608",
                facilities: "Advanced cardiac care, Organ transplant, Robotic surgery, International patient services, Multi-specialty clinics",
                contact_person_phone_number: ["+65-6234-5678", "+65-6234-5679"],
                contact_person_email: ["info@singaporegeneral.com"],
                remarks: "Premium international healthcare provider",
            },
            {
                country_name: "Thailand",
                hospital_name: "Bumrungrad International Hospital",
                division_name: null,
                district_name: null,
                area_name: null,
                address: "33 Sukhumvit 3, Wattana, Bangkok 10110, Thailand",
                facilities: "Oncology, Cardiac, Orthopedics, Neurology, Transplant, 65+ specialties, International patient lounge",
                contact_person_phone_number: ["+66-2-066-8888"],
                contact_person_email: ["international@bumrungrad.com"],
                remarks: "JCI Accredited – Over 50,000 international patients per year",
            },
            {
                country_name: "India",
                hospital_name: "Apollo Hospital Chennai",
                division_name: null,
                district_name: null,
                area_name: null,
                address: "21, Greams Lane, Off Greams Road, Chennai-600006, India",
                facilities: "Cardiac surgery, Bone marrow transplant, Neurosurgery, Robotic surgery, Oncology, Nephrology",
                contact_person_phone_number: ["+91-44-28290200"],
                contact_person_email: ["intlpatients@apollohospitals.com"],
                remarks: "NABH & JCI Accredited",
            },
            {
                country_name: "India",
                hospital_name: "Fortis Memorial Research Institute",
                division_name: null,
                district_name: null,
                area_name: null,
                address: "Sector 44, Opposite HUDA City Centre, Gurugram-122002, India",
                facilities: "Cardiac care, Neurosciences, Orthopedics, Oncology, Liver transplant, Kidney transplant",
                contact_person_phone_number: ["+91-124-4921021"],
                contact_person_email: ["international@fortishealthcare.com"],
                remarks: "Top-ranked multi-specialty hospital in India",
            },
            {
                country_name: "Malaysia",
                hospital_name: "Gleneagles Hospital Kuala Lumpur",
                division_name: null,
                district_name: null,
                area_name: null,
                address: "286 & 288, Jalan Ampang, 50450, Kuala Lumpur, Malaysia",
                facilities: "Cardiac, Oncology, Orthopedics, Neurology, Obstetrics, Pediatrics, International patient services",
                contact_person_phone_number: ["+60-3-4141-3000"],
                contact_person_email: ["gkl@parkwayhealth.com"],
                remarks: "Part of IHH Healthcare group",
            },
            {
                country_name: "Turkey",
                hospital_name: "Anadolu Medical Center",
                division_name: null,
                district_name: null,
                area_name: null,
                address: "Cumhuriyet Mahallesi, 2255. Sokak No: 3, 41400 Gebze/Kocaeli, Turkey",
                facilities: "Oncology, Cardiovascular, Neurology, Orthopedics, Transplant, Stem cell therapy",
                contact_person_phone_number: ["+90-262-678-5000"],
                contact_person_email: ["international@anadolumedical.com"],
                remarks: "JCI Accredited – Johns Hopkins Medicine International affiliate",
            },
        ],
    },
};
