import type { BranchApiSuccessResponse } from '../types';

export const mockBranchData: BranchApiSuccessResponse = {
    success: true,
    transaction_id: "GLIL-TXN-ID",
    data: {
        pagination: {
            current_page: 1,
            total_pages: 5,
            total_records: 47,
            has_next: true,
            has_previous: false,
        },
        branches: [
            {
                office_category: "Main Branch",
                office_name: "Guardian Life Dhanmondi",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Dhanmondi",
                address: "House 12, Road 8, Dhanmondi, Dhaka",
                contact_person_name: "Mr. Ahmed",
                contact_person_email: "ahmed@guardianlife.com",
                contact_person_phone_number: "+880-2-12345678",
            },
            {
                office_category: "Regional Office",
                office_name: "Guardian Life Chittagong",
                division_name: "Chittagong",
                district_name: "Chittagong",
                area_name: "Agrabad",
                address: "Plot 45, Agrabad C/A, Chittagong",
                contact_person_name: "Ms. Rahman",
                contact_person_email: null,
                contact_person_phone_number: "+880-31-123456",
            },
            {
                office_category: "Branch Office",
                office_name: "Guardian Life Sylhet",
                division_name: "Sylhet",
                district_name: "Sylhet",
                area_name: "Zindabazar",
                address: "Building 7, Zindabazar, Sylhet",
                contact_person_name: "Mr. Karim",
                contact_person_email: "karim@guardianlife.com",
                contact_person_phone_number: "+880-821-123456",
            },
            {
                office_category: "Branch Office",
                office_name: "Guardian Life Rajshahi",
                division_name: "Rajshahi",
                district_name: "Rajshahi",
                area_name: "Shaheb Bazar",
                address: "House 3, Shaheb Bazar, Rajshahi",
                contact_person_name: "Ms. Begum",
                contact_person_email: null,
                contact_person_phone_number: "+880-721-654321",
            },
            {
                office_category: "Sub-Branch",
                office_name: "Guardian Life Khulna",
                division_name: "Khulna",
                district_name: "Khulna",
                area_name: "KDA Avenue",
                address: "Plot 22, KDA Avenue, Khulna",
                contact_person_name: "Mr. Islam",
                contact_person_email: "islam@guardianlife.com",
                contact_person_phone_number: "+880-41-123456",
            },
            {
                office_category: "Regional Office",
                office_name: "Guardian Life Barisal",
                division_name: "Barisal",
                district_name: "Barisal",
                area_name: "Sadar Road",
                address: "House 11, Sadar Road, Barisal",
                contact_person_name: "Ms. Akter",
                contact_person_email: "akter@guardianlife.com",
                contact_person_phone_number: "+880-431-65432",
            },
            {
                office_category: "Sub-Branch",
                office_name: "Guardian Life Rangpur",
                division_name: "Rangpur",
                district_name: "Rangpur",
                area_name: "Station Road",
                address: "Block C, Station Road, Rangpur",
                contact_person_name: "Mr. Hossain",
                contact_person_email: null,
                contact_person_phone_number: "+880-521-78901",
            },
            {
                office_category: "Main Branch",
                office_name: "Guardian Life Motijheel",
                division_name: "Dhaka",
                district_name: "Dhaka",
                area_name: "Motijheel",
                address: "Dilkusha C/A, Motijheel, Dhaka",
                contact_person_name: "Mr. Khan",
                contact_person_email: "khan@guardianlife.com",
                contact_person_phone_number: "+880-2-9876543",
            },
            {
                office_category: "Branch Office",
                office_name: "Guardian Life Comilla",
                division_name: "Chittagong",
                district_name: "Comilla",
                area_name: "Kandirpar",
                address: "Road 5, Kandirpar, Comilla",
                contact_person_name: "Ms. Mitu",
                contact_person_email: null,
                contact_person_phone_number: "+880-81-456789",
            },
            {
                office_category: "Sub-Branch",
                office_name: "Guardian Life Mymensingh",
                division_name: "Mymensingh",
                district_name: "Mymensingh",
                area_name: "Ganginarpar",
                address: "House 9, Ganginarpar, Mymensingh",
                contact_person_name: "Mr. Salam",
                contact_person_email: "salam@guardianlife.com",
                contact_person_phone_number: "+880-91-234567",
            },
        ],
    },
};
